import Link from "next/link";
import { course } from "@/lib/content/course";
import AuthButton from "@/components/AuthButton";
import { readTaskSections } from "@/lib/content/taskSections";
import WorkspaceLauncher from "@/components/WorkspaceLauncher";

export default function Courses() {
  return <main className="min-h-screen bg-[#f5f7f4] text-slate-900"><header className="border-b border-slate-200/80 bg-white/90"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 lg:px-8"><Link href="/" className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-teal-700 text-sm font-bold text-white">創</span><span className="font-semibold">創客學院</span></Link><div className="flex items-center gap-3"><AuthButton /><Link href="/teacher" className="hidden rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-600 hover:bg-teal-50 hover:text-teal-700 sm:inline">教師後台</Link><span className="hidden rounded-full bg-teal-50 px-3 py-1.5 text-xs font-semibold text-teal-700 md:inline">學員工作區</span></div></div></header><div className="mx-auto max-w-6xl px-5 py-10 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.2em] text-teal-700">My learning path</p><h1 className="mt-3 text-4xl font-bold tracking-tight md:text-5xl">{course.title}</h1><p className="mt-4 text-lg leading-8 text-slate-600">每個階段都會把觀念拆成短步驟，接著直接完成一份可以帶走的商業成果。</p></div><WorkspaceLauncher courseKey={course.key} courseTitle={course.title} stageOptions={course.stages.map((stage) => ({ key: stage.key, title: stage.title }))} /><div className="mt-10 grid gap-5 md:grid-cols-2">{course.stages.map((stage, index) => { const taskCount = readTaskSections(stage.key); return <div key={stage.key} className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200/70"><div className="flex items-center justify-between"><span className="rounded-full bg-teal-50 px-3 py-1 text-xs font-bold text-teal-700">階段 {String(index + 1).padStart(2, "0")}</span><span className="text-sm text-slate-400">{taskCount.length} 個任務</span></div><h2 className="mt-6 text-2xl font-bold">{stage.title}</h2><p className="mt-3 min-h-12 leading-7 text-slate-600">{stage.summary}</p><div className="mt-8 border-t border-slate-100 pt-4 text-sm"><span className="text-slate-500">理解 → 練習 → 完成</span><p className="mt-2 font-semibold text-teal-700">請先在上方建立或選擇作業 →</p></div></div>; })}</div><section className="mt-10 rounded-3xl bg-slate-900 p-6 text-white md:p-8"><p className="text-sm font-semibold text-teal-300">學習提醒</p><h2 className="mt-2 text-2xl font-bold">不要只看懂，請留下你的版本。</h2><p className="mt-3 max-w-2xl leading-7 text-slate-300">每份作業都有獨立名稱與進度；登入 Supabase 後，答案會同步到你的帳號，不會再自動載入其他作業。</p></section></div></main>;
}
